---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: samayochita
  become: false
  
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "samayochita/spe"
        source: pull
      register: docker_pull_result


    - name: Remove container
      shell: docker rm -f spe

    - name: Running container
      shell: docker run -it -d --name spe samayochita/spe
